version: "3.8"

services:
  ztguard-portal:
    build: .
    container_name: ztguard-portal
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
      - /opt/pangolin-branding/logos:/app/brand-logos
      - /opt/pangolin-branding:/app/pangolin-css
      - /opt/pangolin/config/db:/app/pangolin-db:ro
      - /opt/pangolin/config:/app/pangolin-config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pangolin
    labels:
      - "traefik.enable=false"

networks:
  pangolin:
    external: true
